name: 🔄 Automated Updates

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  workflow_dispatch:

jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    name: 📦 Dependency Updates
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 🔄 Update Dependencies
      run: |
        npm update
        npm audit fix --force
        
    - name: 🧪 Test Updates
      run: npm run validate-all
      
    - name: 🚀 Create PR if Changes
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: automated dependency updates'
        title: '🔄 Automated Dependency Updates'
        body: |
          ## 🔄 Automated Dependency Updates
          
          This PR contains automated dependency updates:
          - Security patches applied
          - Minor version updates
          - Development dependencies refreshed
          
          ### ✅ Quality Checks
          - [ ] All tests pass
          - [ ] No breaking changes detected
          - [ ] Security vulnerabilities resolved
          
          **Auto-generated by GitHub Actions**
        branch: chore/dependency-updates

  quality-monitoring:
    runs-on: ubuntu-latest
    name: 📊 Quality Monitoring
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
      
    - name: 📊 Generate Quality Report
      run: npm run quality-monitoring
      
    - name: 📈 Update Quality Badge
      run: npm run update-quality-badge
